# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: .js
email: intelleej@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jay's Notes
url: "https://clarit7.github.io" # the base hostname & protocol for your site

baseurl: ""
permalink: /:title/

analytics: G-N9CD29WESJ
disqus-shortname: clarit7-github-io
    
# Color schemes
color-1: '#26B99A'
color-2: '#547980'

# Author pictre 100x100 --> keep it inside img folder.
author-image: 'author.jpg'
author-name: 'Jay Lee' 
author-about: 'Senior Researcher, Data Science Cell, Hana Institute of Technology' 

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

sass:
    style: compressed

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
  
prose:
  rooturl: ''
  siteurl: 'https://prose.github.io/starter/'
  relativeLinks: 'https://prose.github.io/starter/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    
gems: [jekyll-seo-tag]
